name: CI/CD FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-app:latest

      - name: Checkout do repositório de manifests
        uses: actions/checkout@v4
        with:
          repository: DaniloLustosa-eng/MANIFESTOS-AGCD-COMPASS
          path: manifests
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update deployment manifest
        run: |
          sed -i 's|image:.*|image: '"${{ secrets.DOCKER_USERNAME }}/hello-app:latest"'|g' manifests/deployment.yaml
          cd manifests
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Atualizando imagem para nova versão"
          git push origin main


